name: Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push frontend image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest 891377218927.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
          docker push 891377218927.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest

      - name: Build, tag, and push backend image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest 891377218927.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          docker push 891377218927.dkr.ecr.ap-south-1.amazonaws.com/backend:latest

      - name: Build, tag, and push database image
        run: |
          docker pull mysql:5.7
          docker tag mysql:5.7 891377218927.dkr.ecr.ap-south-1.amazonaws.com/database:latest
          docker push 891377218927.dkr.ecr.ap-south-1.amazonaws.com/database:latest

      - name: Update Kubernetes configuration
        run: |
          kubectl apply -f k8s-configs/frontend.yaml
          kubectl apply -f k8s-configs/backend.yaml
          kubectl apply -f k8s-configs/database.yaml
